services:
  backend:
    build:
      context: .
      dockerfile: project/backend/Dockerfile
    container_name: azercell-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIAXNV2A6PTCRL5H44X}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-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}
      - KNOWLEDGE_BASE_ID=${KNOWLEDGE_BASE_ID:-JGMPKF6VEI}
    networks:
      - azercell-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: project/frontend/Dockerfile
    container_name: azercell-frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - azercell-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  azercell-network:
    driver: bridge
