name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup uv (+ Python 3.13)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Ruff check
        run: uvx ruff check --output-format=github . --extend-exclude '*.ipynb'
      
      - name: Ruff format check
        run: uvx ruff format --check .
      
      - name: Import sorting check
        run: uvx ruff check --select I .
