name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup uv (+ Python 3.13)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Ruff check
        run: uvx ruff check --output-format=github . --extend-exclude '*.ipynb'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r frontend/requirements.txt
    
    - name: Test backend imports
      run: |
        cd project/backend
        python -c "import fastapi, uvicorn, boto3, pydantic; print('Backend dependencies OK')"
    
    - name: Test frontend imports
      run: |
        cd project/frontend
        python -c "import streamlit, requests; print('Frontend dependencies OK')"
    
    - name: Check application files exist
      run: |
        ls -la project/backend/
        ls -la project/frontend/
        echo "Application files check completed"
